# Generated by Django 4.2 on 2023-04-12 12:41

from django.db import migrations, models
import django.db.models.deletion


def add_root_dir(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Directory = apps.get_model("dataStorageBot", "Directories")
    root = Directory(id=1, title='root')
    root.parent = root
    root.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.directories')),
            ],
            options={
                'db_table': 'directories',
            },
        ),
        migrations.RunPython(add_root_dir),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_file_id', models.TextField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.directories')),
                ('tags', models.ManyToManyField(to='dataStorageBot.tags')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]

