# Generated by Django 4.2 on 2023-05-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirs', to='dataStorageBot.directories')),
            ],
            options={
                'db_table': 'directories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('_current_dir', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataStorageBot.directories')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.users')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_file_id', models.TextField()),
                ('title', models.TextField()),
                ('content_type', models.TextField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.directories')),
                ('tags', models.ManyToManyField(to='dataStorageBot.tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.users')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.AddField(
            model_name='directories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.users'),
        ),
    ]
