# Generated by Django 4.2 on 2023-04-28 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorageBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='directories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.directories'),
        ),
        migrations.AddField(
            model_name='directories',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.users'),
        ),
        migrations.AddField(
            model_name='files',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.users'),
        ),
        migrations.AddField(
            model_name='tags',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dataStorageBot.users'),
        ),
    ]
